[package]
name = "libarchive3-sys"
version = "0.1.0"
authors = ["Jamie Winsor <jamie@vialstudios.com>"]
license = "MIT"
repository = "https://github.com/reset/libarchive-rust"
build = "build.rs"

[dependencies]
libc = ">= 0.2.0"

[build-dependencies]
pkg-config = "*"
